name: LM
on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 20 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: eco4cast/rocker-neon4cast
    env:
      OSN_KEY: ${{ secrets.OSN_KEY }}
      OSN_SECRET: ${{ secrets.OSN_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.OSN_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.OSN_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install R packages
        run: R -e 'source("install.R")'
      - name: Run automatic prediction file (temp_lm)
        run: Rscript ./Generate_forecasts/temp_lm/run_forecast.R
      - name: Back fill forecasts
        run: Rscript ./Generate_forecasts/temp_lm/rerun_forecasts.R
      - name: Health check
        run: Rscript -e "config <- yaml::read_yaml('Generate_forecasts/config.yaml'); RCurl::getURL(config\$models\$tg_dlwrf_lm\$health_check_url)"
